#!/usr/bin/env bash
set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" && cd "$dir"

file="src/amazon/reviews.ts"

npx nodemon -e ts,mjs --delay 0.5 -w "${dir}/../src" -w "${dir}/../dev-resources"  -x "npm run tsx $file"
