name: "CLA Assistant"
on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]')
    permissions:
      contents: read # only need read access for CLA signatures
      pull-requests: write # needed to comment on PRs
      statuses: write # needed to update PR status
      actions: none
      id-token: none
      packages: none

    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: signatures/version1/cla.json
          path-to-document: https://github.com/xhrdev/examples/blob/master/CLA.md
          branch: cla-signatures
          allowlist: skilbjo,dependabot,dependabot[bot]
