# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: cleanup pr caches

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup-pr-caches:
    runs-on: ubuntu-slim
    permissions:
      actions: write
    steps:
      - name: Delete caches scoped to this PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
        run: |
          gh extension install actions/gh-actions-cache
          set +e
          gh actions-cache list -R "$REPO" -B "$BRANCH" -L 100 | cut -f 1 | while IFS= read -r cacheKey; do
            gh actions-cache delete "$cacheKey" -R "$REPO" -B "$BRANCH" --confirm
          done
